### ISSUE TITLE
Misprint in Surah Al-Kafirun

### ISSUE THREAD

**Issue by kaisinux** [Quran-Bundle/quran#1]
When using this code to display Surah Al-Kafirun, the أنا is followed by an unknown character that looks lilke "[]".

```
\documentclass[14pt]{extarticle}

\usepackage[uthmani]{quran}
\usepackage{polyglossia}
\setmainlanguage[numerals=maghrib]{arabic}
\setotherlanguage{english}

\newfontfamily\arabicfont[Script=Arabic,Scale=1.8]{Traditional Arabic}

\usepackage{bidi}


\begin{document}

\quransurah*[109]

\end{document}
```

Has this issue been reported before in a context other than github ?
![kafirun](https://user-images.githubusercontent.com/23412840/56764942-ec9b2000-6773-11e9-8862-9b0694a58197.JPG)

**Comment by javadr** [comment]
I think your font is obsolete, and it does not have that glyph. 
I strongly suggest you install a new version of the font. I have no problem with the code, see the following picture. 
![Screenshot-20190426010244-1148x261](https://user-images.githubusercontent.com/1178221/56766590-06158980-67bf-11e9-9a95-a272b6d008da.png)
