### ISSUE TITLE
Uthmani script does not show waqf stops

### ISSUE THREAD

**Issue by IsmailSalemSukkar** [Quran-Bundle/quran#10]
Salam,

When using uthmani script, waqf stops are not shown. 

The below is printed when the uthmani option is omitted:

`قالوا إِنّا تَطَيَّرنا بِكُم ۖلَئِن لَم تَنتَهوا
لَنَرجُمَنَّكُم وَلَيَمَسَّنَّكُم مِنّا عَذاب ٌأَليم`

The below is printed when using the uthmani option:

`قَالُوٓا ۟إِنَّا تَطَيَّرْنَا بِكُم ْلَئِن لَّم ْتَنتَهُوا
لَنَرْجُمَنَّكُم ْوَلَيَمَسَّنَّكُم م͏ِّنَّا عَذَاب ٌأَلِيم`

Font used is Scheherazade. It appears the waqf gets overriden

**Comment by javadr** [comment]
I didn't understand what you mean exactly! Are you saying that `waqf` is a `sokon`?

As you may have noticed, the `quran` package offers two options for typesetting its text: `simple` text and `uthmai` text. In the former, we use the fewest possible diacritics, while in the latter, you will see more diacritical text.

**Comment by IsmailSalemSukkar** [comment]
No, it is not a sukun. The uthmani text does not show the waqf symbols at all.

Simple:
 
![image](https://github.com/javadr/quran/assets/111706007/117d0cf2-3b71-45a2-9974-e37369518503)

Uthmani:
![image](https://github.com/javadr/quran/assets/111706007/62fc8fbc-b509-45ff-929d-be75bf58422d)

**Comment by javadr** [comment]
Thank you for your clarification. In the previous post, it wasn't clear. I will work on it.

**Comment by javadr** [comment]
Thank you once again for your report.
The issue has been resolved in the latest update.
I will upload it to CTAN, and it will be accessible within the next few hours.
