### ISSUE TITLE
Adding Indonesia Translation

### ISSUE THREAD

**Issue by fakhrisatu** [Quran-Bundle/quran#11]
Hi. 
I'm glad this package exists and is still maintained.
I want to help with adding Indonesian translation. But I don't know how. Can you give me some instructions?

**Comment by javadr** [comment]
Hello @efade,

I've created the [quran-id](https://chat.openai.com/c/github.com/javadr/quran-id) package for Indonesian translation. It has been uploaded to CTAN and will be available in their repositories within the next 24 hours.

Would you be able to test it to ensure that everything is working smoothly?
