### ISSUE TITLE
Feature Request: Spanish Translation

### ISSUE THREAD

**Issue by IsmailSalemSukkar** [Quran-Bundle/quran#12]
Salam Alaikum, 

Would a spanish translation be able to be added to the translation options? 

Jazakallahu khairan

**Comment by javadr** [comment]
Thanks for your suggestion, I will work on it in the near future.

**Comment by javadr** [comment]
The package is now complete and accessible via [GitHub](https://github.com/javadr/quran-es).

It has also been uploaded to [CTAN](https://www.ctan.org/pkg/quran-es) and should be available through its repositories within the next 24 hours.
