### ISSUE TITLE
Tajweed Stops

### ISSUE THREAD

**Issue by ercancem** [Quran-Bundle/quran#13]
Is it possible to output the text with the tajweed stops? If not, is it possible to make it possible?

**Comment by javadr** [comment]
Could you please elaborate more about Tajweed stops?

**Comment by ercancem** [comment]
![latex](https://github.com/javadr/quran/assets/535418/f7a3c61d-c38f-4a38-94ec-7ee4dc572f75)

The tajweed symbols that guide the reciter. (The symbol inside the square box.) I want to be able to ignore them altogether.

**Comment by javadr** [comment]
Ok, you meant Waqf symbols. 
Yes, you can typeset the text without them. Use `wordwise` option like the following. For more information, read the package manual.
In this case, you must use just the `quranayah` macro with its third parameter.

```
\documentclass{article}

\usepackage{arabxetex}
\usepackage[wordwise]{quran}

\begin{document}

    \begin{arab}[utf]
        \quranayah*[2][1-5][1]
    \end{arab}

\end{document}
```
![image](https://github.com/javadr/quran/assets/1178221/053b51eb-a5de-4bc8-8b1e-49cd3a3523c0)

**Comment by ercancem** [comment]
How does this work with arabluatex?
For example:

```
\documentclass[12pt, border=1pc]{standalone}
\usepackage[voc]{arabluatex}
\usepackage[nopar, wordwise]{quran}
\begin{document}
    \begin{txarab}
        \quranayah*[12][1]
    \end{txarab}
\end{document}
```

**Comment by javadr** [comment]
I am afraid, that this option does not work with `lualatex`. 

Could you compile your doc with `xelatex`?

**Comment by javadr** [comment]
I am afraid, that this option does not work with `lualatex`. 

Could you compile your doc with `xelatex`?

**Comment by ercancem** [comment]
(1) Thanks for your time.

(2) Things are sorted out now. (Using arabluatex.) But I still cannot find this info in your package documentation. Where is it exactly?

(3) How do I OMIT the basmala in the output? Say, in this `\quranayah*[12][1-3][1]`

**Comment by javadr** [comment]
2) OMG, you've have forgotten the third parameter I mentioned above!

`\quranayah*[12][1][1]`

![image](https://github.com/javadr/quran/assets/1178221/6f1f43cc-2555-42ba-b7c4-db144a545da4)


3) Apply like this `{\ToggleBasmalah\quranayah[12][1-3][1]}`
