### ISSUE TITLE
How can we add our local translation?

### ISSUE THREAD

**Issue by EmonHaque** [Quran-Bundle/quran#2]
Can we link our local translation to your package and use that in latex document?

**Comment by javadr** [comment]
Yes, you can. You could implement it in the way that the `quran` package did. 
Let me know If you need help.

**Comment by EmonHaque** [comment]
@javadr thanks for your response. I've surah no., ayah no. and translation in an excel file, which I wrote, a few years ago, when I read bangla translation of Quran. 

I'm familiar with C# and, to some extent, Qt/C++ BUT never did anything useful with lua other than using a lua script (2/3 functions) to generate some text and tables in latex document. Anyway, help me with the process of adding those translation in a package so that I can get those in latex document automatically.

**Comment by javadr** [comment]
@EmonHaque 
Please take a look at http://tanzil.net/trans/. 
If your desired language is on that list, I will make it for you. Just let me know you want it or not. 
But if you don't see it in the `tanzil` list I will not work on it as I can not proofread your translation. 
BTW, knowing something about `TeX/LaTeX` makes you capable of building your own package based on the `quran` package's macros.

**Comment by EmonHaque** [comment]
Yes,
There are two Bengali translations in that list:

Bengali জহুরুল হক Zohurul Hoque *
Bengali মুহিউদ্দীন খান Muhiuddin Khan

You could choose any or, if possible, both.

Thank you for your kindness.

**Comment by javadr** [comment]
@EmonHaque Hope you're doing well and safe from COVID19. 

I've almost finished the `quran-bn` package. But I have an issue with one of the translations gotten from [tanzil](http://tanzil.net/trans/bn.bengali).
As you guess, I am not capable of reading Bengali text. 
There are some unusual characters in the mentioned file. 
Could you help me with this issue. The followings are the problematic lines in the translation file:

3|125|অবশ্য তোমরা যদি সবর কর এবং বিরত থাক আর তারা যদি তখনই তোমাদের উপর চড়াও হয়, তাহলে তোমাদের পালনকর্তা চিহিߦ#2468; ঘোড়ার উপর পাঁচ হাজার ফেরেশতা তোমাদের সাহায্যে পাঠাতে পারেন।
5|9|যারা বিশ্বাস স্থাপন করে, এবং সৎকর্ম সম্পাদন করে, আল্লাহ তা˦#2503;দরকে ক্ষমা ও মহান প্রতিদানের প্রতিশ্রুতি দিয়েছেন।
6|83|এটি ছিল আমার যুক্তি, যা আমি ইব্রাহীমকে তাঁর সম্প্রަ#2470;ায়ের বিপক্ষে প্রদান করেছিলাম। আমি যাকে ইচ্ছা মর্যাদায় সমুন্নত করি। আপনার পালনকর্তা প্রজ্ঞাময়, মহাজ্ঞানী
11|40|অবশেষে যখন আমার হুকুম এসে পৌঁছাল এবং ভুপৃষ্ঠ উচ্ছসিত হয়ে উঠল, আমি বললামঃ সর্বপ্রকার জোড়ার দুটি করে এবং যাদের উপরে পূর্বহেߦ#2439; হুকুম হয়ে গেছে তাদের বাদি দিয়ে, আপনার পরিজনবর্গ ও সকল ঈমানদারগণকে নৌকায় তুলে নিন। বলাবাহুল্য অতি অল্পসংখ্যক লোকই তাঁর সাথে ঈমান এনেছিল।
12|76|অতঃপর ইউসুফ আপন ভাইদের থলের পূর্বে তাদের থলে তল্লাশী শুরু করলেন। অবশেষে সেই পাত্র আপন ভাইয়ের থলের মধ্য থেকে বের করলেন। এমনিভাবে আমি ইউসুফকে কৌশল শিক্ষা দিয়েছিলাম। সে বাদশাহর আইনে আপন ভাইকে কখনও দাসত্বে দিতে পারত না, কিু栦#2438;ল্লাহ যদি ইচ্ছা করেন। আমি যাকে ইচ্ছা, মর্যাদায় উন্নীত করি এবং প্রত্যেক জ্ঞানীর উপরে আছে অধিকতর এক জ্ঞানীজন।
16|7|এরা তোমাদের বোঝা এমন শহর পর্যন্ত বহন করে নিয়ে যায়, যেখানে তোমরা প্রাণান্তকর পরিশ্রۦ#2478; ব্যতীত পৌছাতে পারতে না। নিশ্চয় তোমাদের প্রভু অত্যন্ত দয়াদ্র, পরম দয়ালু।
20|96|সে বললঃ আমি দেখলাম যা অন্যেরা দেখেনি। অতঃপর আমি সেই প্রেরিত ব্যক্তির পদচিহেߦ#2480; নীচ থেকে এক মুঠি মাটি নিয়ে নিলাম। অতঃপর আমি তা নিক্ষেপ করলাম। আমাকে আমার মন এই মন্ত্রণাই দিল।
28|40|অতঃপর আমি তাকে ও তার বাহিনীকে পাকড়াও করলাম, তৎপর আমি তাদেরকে সমু˦#2503;দ্র নিক্ষেপ করলাম। অতএব, দেখ জালেমদের পরিণাম কি হয়েছে।
30|18|এবং অপরাহেߠও মধ্যাহেߦ#2404; নভোমন্ডল ও ভূমন্ডলে, তাঁরই প্রসংসা।
47|4|অতঃপর যখন তোমরা কাফেরদের সাথে যুদ্ধে অবতীর্ণ হও, তখন তাদের গর্দার মার, অবশেষে যখন তা˦#2503;দরকে পূর্ণরূপে পরাভূত কর তখন তাদেরকে শক্ত করে বেধে ফেল। অতঃপর হয় তাদের প্রতি অনুগ্রহ কর, না হয় তাদের নিকট হতে মুক্তিপণ লও। তোমরা যুদ্ধ চালিয়ে যাবে যে পর্যন্ত নাশত্রুপক্ষ অস্ত্র সমর্পণ করবে! একথা শুনলে। আল্লাহ ইচ্ছা করলে তাদের কাছ থেকে প্রতিশোধ নিতে পারতেন। কিন্তু তিনি তোমাদের কতককে কতকের দ্বারা পরীক্ষা করতে চান। যারা আল্লাহর পথে শহীদ হয়, আল্লাহ কখনই তাদের কর্ম বিনষ্ট করবেন না।
51|34|যা সীমাতিক্রমকারীদের জন্যে আপনার পালনকর্তার কাছে চিহিߦ#2468; আছে।

What are these character in the above:
#2404;
#2438;
#2439;
#2468;
#2470;
#2478;
#2480;
#2503;
Actually, I know these are some unicode characters, but I have no idea how to put them in a correct way.

**Comment by EmonHaque** [comment]
I've searched those verse nos. here in the link: Al Quran: Digital
<http://www.quran.gov.bd/> by Islamic Foundation, Bangladesh Government.
and here's the list:

3|125| চিহিߦ#2468; = চিহ্নিত
5|9| তা˦#2503;দরকে = তাহাদেরকে
6|83| সম্প্রަ#2470;ায়ের = সম্প্রদায়ের
11|40 পূর্বহেߦ#2439; হুকুম হয়ে গেছে তাদের বাদি দিয়ে = পূর্ব-সিদ্ধান্ত হয়ে
গেছে তাদের বাদ দিয়ে
12|76| কিু栦#2438;ল্লাহ = কিন্তু আল্লাহ
16|7| পরিশ্রۦ#2478; = পরিশ্রম
20|96| পদচিহেߦ#2480; = পদচিহ্নের
28|40| সমু˦#2503;দ্র নিক্ষেপ = সমুদ্রে নিক্ষেপ
30|18| অপরাহেߠও মধ্যাহেߦ#2404; = অপরাহ্নে ও মধ্যাহ্নে
47|4| তা˦#2503;দরকে = তাহাদেরকে
51|34| চিহিߦ#2468; = চিহ্নিত

looks like tanzil.net/trans/bn.bengali has some mistakes, for example, in
11|40 instead of বাদি দিয়ে it should be বাদ দিয়ে

Anyway, thank you a lot for your effort!

**Comment by javadr** [comment]
جزاک الله خیرا

I made your corrections in the source file of translation. But in the case of 11|40, I just found বাদ দিয়ে, not বাদি দিয়ে. 
BTW, it seems this issue has been propagated through the internet as many sites have used the [tanzil](tanzil.net)'s sources for their works. The following picture, for example, shows one of them chosen from [this link](https://al-quran.info/#3). (you can also find the other ones, I mean those typos mentioned above)
![Screenshot from 2021-02-01 10-36-36](https://user-images.githubusercontent.com/1178221/106425621-6009af80-6479-11eb-9558-3fc830a0cb9a.png) 

I've to choose one of these two translations as the default one for the package. Do you have any idea which one is better?

**Comment by EmonHaque** [comment]
I've read only one translation in the translated version of Tafsir Ibn
Kathir (translated by Dr. Muhammad Mujibur Rahman, Professor, Rajshahi
University, Bangladesh). I don't have any idea which translation is better
because of my lack of understanding Arabic. I only can read arabic text
(with vowel signs and tanwin) BUT in no way I'm fluent in reading.

So you could choose either one of your choices.

**Comment by javadr** [comment]
You know, I want to opt for the `khan` translation as a default without any scientific reason!

BTW, if you think this is not a good choice, let me know your opinion.

**Comment by EmonHaque** [comment]
What I've read about Maulanan Muhiuddin Khan is he is famous for
translating a tafsir named Maariful Quran and in fact that was the first
translated tafsir I started with when studying Qur'an and there I'd found
numerous references of famous Tafsir ibn Kathir as I was going through
and eventually that lured me to download the translation of Tafsir Ibn
Kathir and finished reading that instead of continuing Maariful Quran. I
also have read that his translation of Maariful Quran has been published by
the Islamic Foundation of Bangladesh Government.

So I believe his translation will be a good choice as default.

**Comment by javadr** [comment]
Thank you. 

I have just uploaded the `quran-bn` package to the CTAN. Thus, you can update your tex distribution for the next 24 hours to get it.

**Comment by EmonHaque** [comment]
Thanks!
