### ISSUE TITLE
Amiri font

### ISSUE THREAD

**Issue by ercancem** [Quran-Bundle/quran#6]
(1) I am using `LuaLaTeX`. Does the `quran` package use the latest version of the` Amiri` font, or is it better if I load the updated version myself?

(2) `Amiri` font has a variant called `AmiriQuranColored.ttf`, what is the use of that variant?

**Comment by javadr** [comment]
1- The `quran` package does not load any fonts.

2- See [this issue](https://github.com/javadr/quran/issues/5). 
TLDR: for typesetting the text with colorized diacritics (haraka).
