### ISSUE TITLE
Simpler english translation

### ISSUE THREAD

**Issue by XBZWINtj** [Quran-Bundle/quran#7]
Ahmed Ali is a good translation but it would be nice to have a easier to understand translation for those of us who aren't as fluent in english. I would recommend Sahih International.

**Comment by javadr** [comment]
Ok. I will make another package for all English translations proposed by [tanzil](tanzil.net).

**Comment by XBZWINtj** [comment]
Jazakallah khair

**Comment by Shubbak** [comment]
I would also ask for multiple option in german. I personally would Chose the Translation by Frank Bubenheim. jazakallahu kharyan

**Comment by javadr** [comment]
You may already be aware that I have created the `quran-de` package for various German translations. However, since I have utilized the tanzil.net repository as the source for these translations, I do not have access to Frans Bubenheim's translation. Could you please provide guidance on obtaining this particular translation?

**Comment by javadr** [comment]
> Jazakallah khair



> Ahmed Ali is a good translation but it would be nice to have a easier to understand translation for those of us who aren't as fluent in english. I would recommend Sahih International.

@XBZWINtj

Could you kindly review [this link](https://tanzil.net/trans/) and suggest which translations would be suitable for inclusion in the package? While I have the capability to add all of them, it would significantly increase the package size, which I'd like to avoid. Your input on selecting a subset of about 4-7 translations would be appreciated.
As soon as you create it, I'll start working on it.

**Comment by javadr** [comment]
@XBZWINtj 
I've recently uploaded the [`quran-en`](https://ctan.org/pkg/quran-en) package to CTAN. You'll be able to access it within the next 24 hours. This package incorporates all the English translations from [tanzil.net](tanzil.net).
