### ISSUE TITLE
Arabic ayah number digits are in reversed order

### ISSUE THREAD

**Issue by danishbelal** [Quran-Bundle/quran#8]
Salam,

thank you very much for this amazing package.  It serves me a good purpose.  However, I noticed, that the Ayah number digits are rendered from right to left instead of left to right.  Eg. 21 is shown as ١٢.  This only happens when compiling with LuaLaTeX, XeLaTeX renders it correctly.  Unfortunately, I cannot easily transition my document to XeLaTeX.

Are you aware of a workaround that fixes this? I'd highly appreciate it.

This can be reproduced with this example:
```
\documentclass{article}
\usepackage{quran}
\usepackage{fontspec}

\usepackage{polyglossia}
\setdefaultlanguage{english}
\setotherlanguage{arabic}

\setmainfont{Amiri}

\begin{document}
    \textarabic{\quranayah[89][21-24]}
\end{document}
```

Compile it with `lualatex <file>`.

Here is the output:
![grafik](https://user-images.githubusercontent.com/1886637/216114024-6340d968-c3c0-45c9-8da6-d4c40648a571.png)

**Comment by javadr** [comment]
This is an issue with `polyglossia` and `lualatex`, I think. 
Test \textarabic{1234} and see the result, `4321`!

**Comment by seloumi** [comment]
How about `babel` package ?
```latex
\documentclass{article}
\usepackage{quran}
\usepackage[bidi=basic,english]{babel}

\babelprovide[import]{arabic}

\babelfont{rm}{Amiri}

\begin{document}

\selectlanguage{arabic}
    \quranayah[89][21-24]

\end{document}
```

**Comment by danishbelal** [comment]
This looks promising.  I'll look into it and get back to you.  Thank you.

**Comment by danishbelal** [comment]
@seloumi your approach works fine as is.  However, I also need to load other fonts via fontspec and it appears that loading fonts through babel conflicts with fontspec.  I cannot use your approach for my purpose, unfortunately :(.
